Create trie.py
AIBauchi/PyDS-A pull request #64
Opened 2023-10-11 17:30 UTC by rghvsh

# PR Description

Adds trie data structure

## Related Issue

Closes: #62 

## Changes Made

List the changes you made in this pull request:

- Adds trie data structure.

## Author

Raghav Sharma (@rghvsh )

2023-10-15 04:59 UTC, rghvsh commented on pyds_a/data_structures/trie.py
> +
sure

2023-10-15 07:08 UTC, rghvsh commented
Hey @Tinny-Robot made some change. Is

2023-10-15 07:15 UTC, rghvsh commented
Hey

2023-10-15 08:10 UTC, rghvsh commented
Hey! @Tinny-Robot checked the other files and made the file analogous , changed its file structure. Is this better?

2023-10-16 03:05 UTC, matt-wisdom requested changes
Hello, there seems to be indentation issues in your code, please ensure that the code is properly indented (make sure the docstrings of each method are on the same indentation level as the code).

2023-10-16 11:08 UTC, rghvsh commented
fixed indentation

2023-10-23 00:02 UTC, merged